name: Tembo CLI workflow

defaults:
  run:
    shell: bash
    working-directory: ./

on:
  pull_request:
    branches:
      - main
  # Always run tests on main or release branches
  push:
    branches:
      - main

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install minimal nightly with clippy and rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "tembo-lint"
          workspaces: |
            tembo
      - name: Cargo format
        run: cargo +nightly fmt --check
      - name: Clippy
        run: cargo clippy
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "tembo-test"
          workspaces: |
            tembo
      - name: Run tests
        run: cargo test
